### ISSUE TITLE
How do I install on Linux?

### ISSUE THREAD

**Issue by CHJ85** [ErikLethDanielsen/radiotray-qt#1]
Hi there. How do I compile this for Linux?
You say this is a Linux software yet your instructions are for Windows.
With all the software choices they have, I think it's odd you even focus on Windows.

**Comment by ErikLethDanielsen** [comment]
Hi
My pc run Debian 10 KDE
You have to install qt-creator first
sudo apt install qtcreator

   1. git clone https://github.com/ErikLethDanielsen/radiotray-qt.git
   2. Open in qt-creator
   3. Run / Build
   4. exe is in /Output folder
   5. Run it.

,Erik

Den ons. 10. nov. 2021 kl. 16.32 skrev CHJ85 ***@***.***>:

**Comment by CHJ85** [comment]
Thank you. I thought because you mentioned EXE those were Windows instructions.
I've never heard of Qtcreator before.
Sorry about the misunderstanding.
